# Mathematical functions

In [80]:
import numpy as np

In [81]:
np.__version__

'1.19.2'

## Trigonometric functions

Calculate sine, cosine, and tangent of x, element-wise.  
Hint: use np.sin(), np.cos(), np.tan()

In [7]:
x = np.array([0., 1., 30, 90])
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))

[ 0.          0.84147098 -0.98803162  0.89399666]
[ 1.          0.54030231  0.15425145 -0.44807362]
[ 0.          1.55740772 -6.4053312  -1.99520041]


sine: [ 0.          0.84147098 -0.98803162  0.89399666]
cosine: [ 1.          0.54030231  0.15425145 -0.44807362]
tangent: [ 0.          1.55740772 -6.4053312  -1.99520041]


Calculate inverse sine, inverse cosine, and inverse tangent of x, element-wise.  
Hint: use np.arcsin(), np.arccos(), np.arctan()

In [8]:
x = np.array([-1., 0, 1.])
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


inverse sine: [-1.57079633  0.          1.57079633]
inverse cosine: [3.14159265 1.57079633 0.        ]
inverse tangent: [-0.78539816  0.          0.78539816]


Convert angles from radians to degrees.  
Hint: use np.degrees() or np.rad2deg()

In [10]:
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])
np.degrees(x)

array([-180.,  -90.,   90.,  180.])

[-180.  -90.   90.  180.]


Convert angles from degrees to radians.  
Hint: use np.radians() or np.deg2rad()

In [12]:
x = np.array([-180.,  -90.,   90.,  180.])
np.radians(x)

array([-3.14159265, -1.57079633,  1.57079633,  3.14159265])

[-3.14159265 -1.57079633  1.57079633  3.14159265]


## Hyperbolic functions

Calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent of x, element-wise.  
Hint: use np.sinh(), np.cosh(), np.tanh()

In [15]:
x = np.array([-1., 0, 1.])
print(np.sinh(x))
print(np.cosh(x))
print(np.tanh(x))

[-1.17520119  0.          1.17520119]
[1.54308063 1.         1.54308063]
[-0.76159416  0.          0.76159416]


[-1.17520119  0.          1.17520119]
[1.54308063 1.         1.54308063]
[-0.76159416  0.          0.76159416]


## Rounding

Round x element-wise  
Hint: use np.around(x) or np.floor(x) or np.ceil(x) or np.trunc(x)

In [20]:
x = np.array([2.1, 1.5, 2.5, 2.9, -2.1, -2.5, -2.9])
print(np.around(x))
print(np.floor(x))
print(np.ceil(x))
print(np.trunc(x))

[ 2.  2.  2.  3. -2. -2. -3.]
[ 2.  1.  2.  2. -3. -3. -3.]
[ 3.  2.  3.  3. -2. -2. -2.]
[ 2.  1.  2.  2. -2. -2. -2.]


[ 2.  2.  2.  3. -2. -2. -3.]
[ 2.  1.  2.  2. -3. -3. -3.]
[ 3.  2.  3.  3. -2. -2. -2.]
[ 2.  1.  2.  2. -2. -2. -2.]


## Sums, products, differences

Calculate the difference between neighboring elements, element-wise.  
Hint: use np.diff()

In [23]:
x = np.array([1, 2, 4, 7, 0])
np.diff(x)

array([ 1,  2,  3, -7])

[ 1  2  3 -7]


Return the cross product of x and y.  
Hint: use np.cross()

In [25]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.cross(x,y)

array([-3,  6, -3])

[-3  6 -3]


## Exponents and logarithms

Compute $e^x$, element-wise.  
Hint: use np.exp()

In [27]:
x = np.array([1., 2., 3.], np.float32)
np.exp(x)

array([ 2.7182817,  7.389056 , 20.085537 ], dtype=float32)

[ 2.7182817  7.389056  20.085537 ]


Calculate exp(x) - 1 for all elements in x.  
Hint: there are np.expm1() and np.exp(), make your own choice and use it properly

In [29]:
x = np.array([1., 2., 3.], np.float32)
np.expm1(x)

array([ 1.7182817,  6.389056 , 19.085537 ], dtype=float32)

[ 1.7182817  6.389056  19.085537 ]


Calculate $2^p$ for all p in x.  
Hint: Refer to the lecture. np.exp2() will help, too.

In [31]:
x = np.array([1., 2., 3.], np.float32)
np.exp2(x)

array([2., 4., 8.], dtype=float32)

[2. 4. 8.]


Compute natural, base 10, and base 2 logarithms of x element-wise.  
Hint: use np.log(), np.log10(), np.log2()

In [35]:
x = np.array([1, np.e, np.e**2])
print(np.log(x))
print(np.log10(x))
print(np.log2(x))

[0. 1. 2.]
[0.         0.43429448 0.86858896]
[0.         1.44269504 2.88539008]


natural log = [0. 1. 2.]
common log = [0.         0.43429448 0.86858896]
base 2 log = [0.         1.44269504 2.88539008]


## Arithmetic operations

Add x and y element-wise.

In [38]:
x = np.array([1, 2, 3])
y = np.array([-1, -2, -3])
print(x+y)

[0 0 0]


[0 0 0]


Subtract y from x element-wise.

In [40]:
x = np.array([3, 4, 5])
y = np.array(3)
print(x-y)

[0 1 2]


[0 1 2]


Multiply x by y element-wise.

In [41]:
x = np.array([3, 4, 5])
y = np.array([1, 0, -1])
print(x*y)

[ 3  0 -5]


[ 3  0 -5]


Divide x by y element-wise

In [42]:
x = np.array([3., 4., 5.])
y = np.array([1., 2., 3.])
print(x/y)

[3.         2.         1.66666667]


[3.         2.         1.66666667]


Compute numerical negative value of x, element-wise.

In [43]:
x = np.array([1, -1])
print(x*-1)

[-1  1]


[-1  1]


Compute the reciprocal of x, element-wise.

In [44]:
x = np.array([1., 2., .2])
print(1/x)

[1.  0.5 5. ]


[1.  0.5 5. ]


Compute $x^y$, element-wise.

In [48]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [1, 2]])
print(x**y)

[[ 1  4]
 [ 3 16]]


[[ 1  4]
 [ 3 16]]


Compute the remainder of x / y element-wise in two different ways.  
Hint: use np.mod() or `%` operator

In [52]:
x = np.array([-3, -2, -1, 1, 2, 3])
y = 2
print(np.mod(x,y))
print(x%y)

[1 0 1 1 0 1]
[1 0 1 1 0 1]


[1 0 1 1 0 1]


## Miscellaneous

If an element of x is smaller than 3, replace it with 3.  
And if an element of x is bigger than 7, replace it with 7.  
Hint: use array masking

In [70]:
x = np.arange(10)
x[x<3] = 3
x[x>7] = 7
print(x)

[3 3 3 3 4 5 6 7 7 7]


[3 3 3 3 4 5 6 7 7 7]


Compute the square of x, element-wise.

In [71]:
x = np.array([1, 2, -1])
print(x*x)

[1 4 1]


[1 4 1]


Compute square root of x element-wise.

In [73]:
x = np.array([1., 4., 9.])
print(np.sqrt(x))

[1. 2. 3.]


[1. 2. 3.]


Compute the absolute value of x.

In [74]:
x = np.array([[1, -1], [3, -3]])
print(np.absolute(x))

[[1 1]
 [3 3]]


[[1 1]
 [3 3]]


Compute an element-wise indication of the sign of x, element-wise.

In [76]:
x = np.array([1, 3, 0, -1, -3])
x[x<0] = -1
x[x>0] = 1
print(x)

[ 1  1  0 -1 -1]


In [78]:
x = np.array([1, 3, 0, -1, -3])
print(np.sign(x))

[ 1  1  0 -1 -1]


[ 1  1  0 -1 -1]
