In [1]:
import numpy as np

In [2]:
arr = np.linspace(1,20,20,dtype=np.int).reshape(5,4)

In [3]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [4]:
arr[1:2,3:4]

array([[8]])

In [6]:
arr[(1),(3)]

8

In [12]:
arr1 = np.linspace(1,36,36).reshape(3,4,3)
arr1

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]],

       [[13., 14., 15.],
        [16., 17., 18.],
        [19., 20., 21.],
        [22., 23., 24.]],

       [[25., 26., 27.],
        [28., 29., 30.],
        [31., 32., 33.],
        [34., 35., 36.]]])

In [16]:
arr1.max(axis=0)

array([[25., 26., 27.],
       [28., 29., 30.],
       [31., 32., 33.],
       [34., 35., 36.]])